### ISSUE TITLE
Flux-style Helm Release versions including OCI artifact ID are not recognized by Nova

### ISSUE THREAD

**Issue by fibbs** [FairwindsOps/nova#354]
### What happened?

I am using Flux to manage my clusters. When using a Flux `HelmRelease` resource together with a `OCIRepository`, having the `HelmRelease` referencing to an artifact in the OCI repository which is the helm chart, which is the new standard, the Helm Release version is represented concatenating the Chart version from the chart's `Chart.yaml` with the OCI artifact hash (or something like that):

```
helm ls
NAME    	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                       	APP VERSION
keycloak	keycloak 	11      	2024-12-26 19:21:36.413229479 +0000 UTC	deployed	keycloak-24.3.1+dbae01c0bd1d	26.0.7
```

Now, when using nova, it doesn't recognize this version as being the same as the upstream one:
```
Release Name              Installed              Latest           Old     Deprecated
============              =========              ======           ===     ==========
keycloak                  24.3.1+dbae01c0bd1d    24.3.1           true    false
```

### What did you expect to happen?

I would have liked Nova to recognize this special versioning and "understand" it. Or to be able to configure this somehow (see #353).

### How can we reproduce this?

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 12h
  provider: generic
  ref:
    tag: 24.3.1
  timeout: 1m
  url: oci://registry-1.docker.io/bitnamicharts/keycloak
```

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  chartRef:
    kind: OCIRepository
    name: keycloak
  interval: 1m0s
  releaseName: keycloak
  valuesFrom:
  - kind: ConfigMap
    name: keycloak-values-4bdk7cdk69
    valuesKey: keycloak-values.yaml
```

### Version

Version:3.11.1 Commit:0affeff0b28c8482e449da5dcaec02915bec2f78

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudermanjr** [comment]
Is this versioning string specific to flux, or is it how Helm shows the version when installing from an OCI registry? I don't believe I've seen this before.

**Comment by fibbs** [comment]
It seems to be flux specific:

```
> helm install keycloak oci://registry-1.docker.io/bitnamicharts/keycloak
```

leads to:
```
helm ls
NAME    	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART          	APP VERSION
keycloak	default  	1       	2025-01-14 16:44:22.694313 +0100 CET	deployed	keycloak-24.4.2	26.0.8
```

But in another cluster, I have a flux `OCIRepository` and a `HelmRelease` resource as follows:

```yaml
apiVersion: v1
items:
- apiVersion: source.toolkit.fluxcd.io/v1beta2
  kind: OCIRepository
  metadata:
    finalizers:
    - finalizers.fluxcd.io
    generation: 7
    labels:
      kustomize.toolkit.fluxcd.io/name: apps
      kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: keycloak
    namespace: keycloak
  spec:
    interval: 12h
    provider: generic
    ref:
      tag: 24.3.1
    timeout: 1m
    url: oci://registry-1.docker.io/bitnamicharts/keycloak
```

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  finalizers:
  - finalizers.fluxcd.io
  generation: 3
  labels:
    kustomize.toolkit.fluxcd.io/name: apps
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: keycloak
  namespace: keycloak
spec:
  chartRef:
    kind: OCIRepository
    name: keycloak
  interval: 1m0s
  releaseName: keycloak
  valuesFrom:
  - kind: ConfigMap
    name: keycloak-values-4bdk7cdk69
    valuesKey: keycloak-values.yaml
```

and the result is:
```
> helm ls
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
keycloak        keycloak        11              2024-12-26 19:21:36.413229479 +0000 UTC deployed        keycloak-24.3.1+dbae01c0bd1d    26.0.7
```

There is [this issue](https://github.com/fluxcd/flux2/issues/4910) showing some other people's problems with this kind of version representation, but it doesn't really have to do with the problem I have with nova.
